version: '3.8'

volumes:
  user_data:  # Volumen para almacenar las bases de datos de los usuarios
    driver: local

networks:
  chat_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  server:
    image: server-image
    container_name: server
    networks:
      chat_network:
        ipv4_address: 192.168.1.2
    stdin_open: true  
    tty: true         

  client1:
    image: client-image
    container_name: client1
    volumes:
      - user_data:/app/user_data
    networks:
      chat_network:
        ipv4_address: 192.168.1.3
    stdin_open: true  
    tty: true         

  client2:
    image: client-image
    container_name: client2
    volumes:
      - user_data:/app/user_data
    networks:
      chat_network:
        ipv4_address: 192.168.1.4
    stdin_open: true  
    tty: true         

  client3:
    image: client-image
    container_name: client3
    volumes:
      - user_data:/app/user_data
    networks:
      chat_network:
        ipv4_address: 192.168.1.5
    stdin_open: true  
    tty: true         
