version: '3.8'

volumes:
  user_data:
    driver: local

networks:
  server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  client_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24

services:
  router:
    image: router-image
    container_name: router
    networks:
      server_network:
        ipv4_address: 192.168.1.100
      client_network:
        ipv4_address: 192.168.2.100
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10

  server1:
    build: .
    image: server-image
    container_name: server1
    environment:
      - LOCAL_IP=192.168.1.2
    networks:
      server_network:
        ipv4_address: 192.168.1.2
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    privileged: true
    cap_add:
      - NET_ADMIN
    # ports:
    #   - "65432:65432" 

  server2:
    build: .
    image: server-image
    container_name: server2
    environment:
      - LOCAL_IP=192.168.1.3
      - JOIN_NODE=192.168.1.2:65433
    networks:
      server_network:
        ipv4_address: 192.168.1.3
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    privileged: true
    cap_add:
      - NET_ADMIN
    # ports:
    #   - "65432:65432" 

  server3:
    build: .
    image: server-image
    container_name: server3
    environment:
      - LOCAL_IP=192.168.1.4
      - JOIN_NODE=192.168.1.2:65433
    networks:
      server_network:
        ipv4_address: 192.168.1.4
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    privileged: true
    cap_add:
      - NET_ADMIN
    # ports:
    #   - "65432:65432" 

  server4:
    build: .
    image: server-image
    container_name: server4
    environment:
      - LOCAL_IP=192.168.1.5
      - JOIN_NODE=192.168.1.2:65433
    networks:
      server_network:
        ipv4_address: 192.168.1.5
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    privileged: true
    cap_add:
      - NET_ADMIN
    # ports:
    #   - "65432:65432" 

  server5:
    build: .
    image: server-image
    container_name: server5
    environment:
      - LOCAL_IP=192.168.1.6
      - JOIN_NODE=192.168.1.2:65433
    networks:
      server_network:
        ipv4_address: 192.168.1.6
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    privileged: true
    cap_add:
      - NET_ADMIN
    # ports:
    #   - "65432:65432" 



  client1:
    image: client-image
    container_name: client1
    volumes:
      - user_data:/app/user_data
    networks:
      client_network:
        ipv4_address: 192.168.2.2
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    extra_hosts:
      - "gateway:192.168.2.100"
    privileged: true
    cap_add:
      - NET_ADMIN

  client2:
    image: client-image
    container_name: client2
    volumes:
      - user_data:/app/user_data
    networks:
      client_network:
        ipv4_address: 192.168.2.3
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    extra_hosts:
      - "gateway:192.168.2.100"
    privileged: true
    cap_add:
      - NET_ADMIN

  client3:
    image: client-image
    container_name: client3
    volumes:
      - user_data:/app/user_data
    networks:
      client_network:
        ipv4_address: 192.168.2.4
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    extra_hosts:
      - "gateway:192.168.2.100"
    privileged: true
    cap_add:
      - NET_ADMIN
